baseURL = 'https://ikramulhasan.me'
languageCode = 'en-us'
title = 'Ikramul Hasans Tiny Little Corner of the Web'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false